# Generated by Django 3.1 on 2020-10-23 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('copies', models.IntegerField(default=1)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('ratings', models.DecimalField(decimal_places=2, max_digits=3)),
                ('short_desc', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('cover_picture', models.ImageField(upload_to='book_photos/')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('genre', models.ManyToManyField(to='books.Genre')),
            ],
        ),
    ]
